export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const NEW_MESSAGE = "NEW_MESSAGE"; //saga
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const FETCH_USER_LIST = "FETCH_USER_LIST";//saga
export const UPD_ROOM_ONL_USERS = "UPD_ROOM_ONL_USERS";
/* export const ADD_USER = "ADD_USER"; */
/* export const USER_LIST = "USER_LIST"; */
export const ENTER_TO_ROOM = "ENTER_TO_ROOM"; //sage
export const FETCH_ROOM_LIST = "FETCH_ROOM_LIST"; //saga
export const UPD_CURR_ROOM = "UPD_CURR_ROOM";
export const UPD_CURR_USER = "UPD_CURR_USER";
export const UPD_ROOM_LIST = "UPD_ROOM_LIST";